use_frameworks!

platform :ios, '8.0'

target 'MXAvroLogValidate_Example' do
  pod 'MXAvroLogValidate', :path => '../'

  target 'MXAvroLogValidate_Tests' do
    inherit! :search_paths

    
  end
end
